src/main/Java/LanguageBean.java
/**
 * Created by vadim.malishev on 21.10.2014.
 */
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

@ManagedBean(name="language")
@SessionScoped
public class LanguageBean implements Serializable{

    private static final long serialVersionUID = 1L;

    private String localeCode;

    private static Map<String,Object> countries;
    static{

        countries = new LinkedHashMap<String,Object>();
        countries.put("English", Locale.ENGLISH); //label, value
        countries.put("Russian", Locale.GERMAN);
    }

    public Map<String, Object> getCountriesInMap() {
        return countries;
    }


    public String getLocaleCode() {
        return localeCode;
    }


    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode;
    }

    //value change event listener
    public void countryLocaleCodeChanged(ValueChangeEvent e){

        String newLocaleValue = e.getNewValue().toString();

        //loop country map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {

            if(entry.getValue().toString().equals(newLocaleValue)){

                FacesContext.getCurrentInstance()
                        .getViewRoot().setLocale((Locale)entry.getValue());

            }
        }
    }

}

src/main/webapp/pages/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"

      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <h:outputStylesheet library="css" name="styles.css"/>
</h:head>
<h:body>
    <ui:composition template="template/tamplate.xhtml">
        <ui:define name="content">
            <h:form>
                <h1>
                    <h:outputText value="#{msg['welcome.jsf']}"/>
                    <br/>
                </h1>

                <h2>
                    <h:outputText value="#{msg['date.jsf']}"/>
                    <br/>
                    <br/>
                    <h:outputText value="#{msg['desc.jsf']}" escape="false"/>
                    <br/>
                    E-mail: <a href="mailto:malysheff@ukr.net"> malysheff@ukr.net</a>
                    <br/>
                    <br/>
                    <!-- anchor education-->
                    <h:commandLink id="education" name="education"/>
                    <br/>
                </h2>

                <h3>
                    <h:outputText value="#{msg['educ_head.jsf']}" escape="false"/>
                </h3>

                <h2>
                    <h:outputText value="#{msg['educ.jsf']}" escape="false"/>
                    <br/>
                    <br/>
                    <!-- anchor skills-->
                    <h:commandLink id="skills" name="skills"/>
                </h2>

                <h3>
                    <h:outputText value="#{msg['skills_head.jsf']}" escape="false"/>
                </h3>

                <h2>
                    <h:outputText value="#{msg['skills.jsf']}" escape="false"/>
                    <br/>
                    <br/>
                    <!-- anchor experience-->
                    <h:commandLink id="exp" name="exp"/>
                </h2>

                <h3>
                    <h:outputText value="#{msg['exp_head.jsf']}" escape="false"/>
                </h3>

                <h2>
                    <h:outputText value="#{msg['exp1.jsf']}" escape="false"/>
                    <br/>

                    <h:outputText value="#{msg['exp2.jsf']}" escape="false"/>
                    <br/>
                    <br/>
                </h2>

                <h3>
                    <h:outputText value="#{msg['add_head.jsf']}" escape="false"/>
                    <!-- anchor additional-->
                    <h:commandLink id="additional" name="additional"/>
                    <br/>
                </h3>
                <h2>
                    <h:outputText value="#{msg['add.jsf']}" escape="false"/>
                </h2>

            </h:form>
        </ui:define>
    </ui:composition>


</h:body>
</html>

src/main/webapp/pages/index_eng.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
    <h:outputStylesheet library="css" name="styles.css"/>
</h:head>
<h:body>
    <ui:composition template="template/tamplate.xhtml">
        <ui:define name="content">

            <!-- <h:form>
                 <p:commandButton id="button1" value="Submit" action="wizard"/>
             </h:form>
             -->
            <table id= "pprint" cellspacing="20" width="100%"/>
            <table border="0" cellpadding="0" cellspacing="0" width="100%"/>
            <tr>
                <td width="100%" colspan="2"><b><font color="#52545F" size="4">Malyshev Vadym</font></b>
                    <br/>
                    <font color="#52545F">Date of dirth: 1978/08/21 </font></td>

            </tr>
            <tr>
                <td width="100%" colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <td width="3%"></td>
                <td width="97%"><font color="#52545F">
                    <br/>
                    Тел. (+38)050-353-32-98
                    <br/>
                    E-mail: <a href="mailto:malysheff@ukr.net"> malysheff@ukr.net</a></font><br/></td>

            </tr>
            <tr>
                <td width="100%" colspan="2">&nbsp;</td>
            </tr>
            <tr>
                <td width="100%" colspan="2"><b><font color="#52545F">Education</font></b><br/></td>
            </tr>
            <tr>
                <td width="3%"></td>
                <td width="97%"><font color="#52545F">National technical university of Ukraine "KPI". Faculty of Computer Science and Engineering.<br/>
                   Specialist, "Computer systems and networks". 1996 - 2002</font></td>
            </tr>


        </ui:define>
    </ui:composition>

</h:body>
</html>

src/main/webapp/pages/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui">

<p:megaMenu orientation="vertical" style="margin-top:20px">
    <p:menuitem value="Go to error page" url="/pages/error/error.xhtml?faces-redirect=true" icon="ui-icon-carat-1-e
 "/>
    <p:menuitem value="Go to index page" url="/pages/index.xhtml" icon="ui-icon-carat-1-e
 "/>
</p:megaMenu>
</html>

src/main/webapp/pages/tabMenu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


<p:tabMenu activeIndex="#{param.i}">
    <p:menuitem value="Go to error page" url="/pages/error/error.xhtml" icon="ui-icon-star">
        <f:param name="i" value="0" />
    </p:menuitem>
    <p:menuitem value="Go to english page" url="/pages/index_eng.xhtml" icon="ui-icon-search">
        <f:param name="i" value="1" />
    </p:menuitem>

</p:tabMenu>

</html>

src/main/webapp/pages/template/tamplate.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
<h:head>
    <meta http-equiv="Content-Type"
          content="text/html; charset=UTF-8"/>
    <title>Facelets Template</title>
    <h:outputStylesheet library="css" name="styles.css"/>
</h:head>

<h:body>

    <p:layout fullPage="true">

        <p:layoutUnit position="north" size="60" header="">
            <h:form>
                <!--
                <span style="padding:0px 10px;">
                <p:link value = "Russian"  href = "/pages/index.xhtml">

                </p:link>
                </span>

                <span style="padding:0px 10px;">
                <p:link value = "English"  href = "/pages/index_eng.xhtml">

                </p:link>
                </span>
                -->
                <h:panelGrid columns="2">

                    Language :
                    <h:selectOneMenu value="#{language.localeCode}" onchange="submit()"
                                     valueChangeListener="#{language.countryLocaleCodeChanged}">
                        <f:selectItems value="#{language.countriesInMap}"/>
                    </h:selectOneMenu>

                </h:panelGrid>

            </h:form>
            <!--ui:include src="../tabMenu.xhtml" ></ui:include-->
        </p:layoutUnit>


        <p:layoutUnit position="west" resizable="true" collapsible="true">
            <h:form>
                <h:graphicImage library="images" name="2.JPG" styleClass="pf-layout-pane-west"/>

                <p:growl autoUpdate="true"/>

                <p:panelMenu>
                    <p:submenu label= "#{msg1['link1.jsf']}"  >
                        <p:menuitem value="#{msg1['link2.jsf']}" url="/pages/index.xhtml#education" icon="ui-icon-disk"/>
                        <p:menuitem value="#{msg1['link3.jsf']}" url="/pages/index.xhtml#skills" icon="ui-icon-disk"/>
                        <p:menuitem value="#{msg1['link4.jsf']}" url="/pages/index.xhtml#exp" icon="ui-icon-disk"/>
                        <p:menuitem value="#{msg1['link5.jsf']}" url="/pages/index.xhtml#additional" icon="ui-icon-disk"/>

                    </p:submenu>

                </p:panelMenu>


            </h:form>

        </p:layoutUnit>


        <p:layoutUnit position="center">
            <ui:insert name="content">""</ui:insert>
        </p:layoutUnit>

    </p:layout>
</h:body>
</html>